# doc: https://docs.brew.sh/Brew-Bundle-and-Brewfile
# install command:
#   brew bundle --file=~/dotfiles/homebrew/Brewfile

brew "git"
brew "gh"
brew "tig"
brew "neovim"
brew "jq"
brew "jnv"

brew "wget"
brew "curl"
brew "tree"
brew "zsh"
brew "coreutils"
brew "grep"
brew "atool"
brew "gpg"
brew "openssl"
brew "readline"
brew "colordiff"

brew "git-now"
brew "peco"
brew "ghq"
brew "mise"
