[[plugins]]
repo = 'Shougo/dein.vim'

# Colorscheme
[[plugins]]
repo = 'dracula/vim'

# Colorscheme
[[plugins]]
repo = 'joedicastro/vim-molokai256'

# Colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'

# 補完
[[plugins]]
repo = 'zxqfl/tabnine-vim'

[[plugins]]
repo = 'bling/vim-airline'
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline_theme='murmur'

  set guifont=Ricty\ Regular\ for\ Powerline:h14
  let g:airline_section_a = airline#section#create(['mode','','branch'])

  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#left_sep = ' '
  let g:airline#extensions#tabline#left_alt_sep = '|'
  let g:airline#extensions#tabline#show_buffers = 0
  let g:airline#extensions#tabline#tab_nr_type = 1
  let g:airline#extensions#tabline#fnamemod = ':t'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  " [Space + f] がPrefix
  nnoremap [Denite] <Nop>
  nmap <Space>f [Denite]

  " カレントディレクトリ
  nnoremap <silent> [Denite]f :<C-u>Denite file buffer<CR>
  " 最近開いたファイル
  nnoremap <silent> [Denite]m :<C-u>Denite file_mru<CR>

  " ESCキーでdeniteを終了
  call denite#custom#map('insert', '<esc>', '<denite:enter_mode:normal>', 'noremap')
  call denite#custom#map('normal', '<esc>', '<denite:quit>', 'noremap')

  " insertモードの時にjjでnormalモードになる
  call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>', 'noremap')

  " [ctrl + v]で横に分割して開く
  call denite#custom#map('insert', '<C-s>', '<denite:do_action:split>', 'noremap')
  call denite#custom#map('normal', '<C-s>', '<denite:do_action:split>', 'noremap')
  " [ctrl + s]で縦に分割して開く
  call denite#custom#map('insert', '<C-v>', '<denite:do_action:vsplit>', 'noremap')
  call denite#custom#map('normal', '<C-v>', '<denite:do_action:vsplit>', 'noremap')

  call denite#custom#map('insert', '<C-w>', '<denite:insert_word:../>', 'noremap')

  " プロンプトを # から > に変更
  call denite#custom#option('default', 'prompt', '>')
  " 表示位置を上部に変更
  call denite#custom#option('default', 'direction', 'top')
  " grepでagを使用するように設定
  call denite#custom#var('grep', 'command', ['ag'])
  " カレントディレクトリ内の検索もagを使用する
  call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = '5t111111/denite-rails'
hook_add = '''
  nnoremap <silent> [Denite]rr :<C-u>Denite<Space>rails:dwim<Return>
  nnoremap <silent> [Denite]rm :<C-u>Denite<Space>rails:model<Return>
  nnoremap <silent> [Denite]rc :<C-u>Denite<Space>rails:controller<Return>
  nnoremap <silent> [Denite]rv :<C-u>Denite<Space>rails:view<Return>
  nnoremap <silent> [Denite]rh :<C-u>Denite<Space>rails:helper<Return>
  nnoremap <silent> [Denite]rt :<C-u>Denite<Space>rails:test<Return>
  nnoremap <silent> [Denite]rs :<C-u>Denite<Space>rails:spec<Return>
'''

# ファイラ
[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
  " C-eでvaffleを開く
  nnoremap <silent><C-e> :Vaffle<Cr>
'''

# Syntax check
[[plugins]]
repo = 'w0rp/ale'

# Gtag
[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
  " 開いているファイルの関数一覧を表示
  nnoremap <C-h> :Gtags -f %<Cr>
  " 関数リストの下移動
  nnoremap <silent> <C-n> :cn<Cr>
  " 関数リストの上移動
  nnoremap <silent> <C-p> :cp<Cr>
  " 調べたい関数にカーソルを合わせてC-mするとジャンプする
  nnoremap <silent> <C-m> :GtagsCursor<Cr>
'''

# タグの非同期更新
[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
  let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_color_term = 239
  let g:indentLine_conceallevel = 2
'''

# テキスト整形
# https://wonderwall.hatenablog.com/entry/2016/03/29/215904
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
  " Start interactive EasyAlign in visual mode (e.g. vipga)
  xmap ga <Plug>(EasyAlign)

  " Start interactive EasyAlign for a motion/text object (e.g. gaip)
  nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'kana/vim-smartword'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

