[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rt']
hook_add = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = ['yaml', 'yml']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf']

[[plugins]]
repo = 'vim-scripts/nginx.vim'
on_ft = ['conf']

[[plugins]]
repo = 'thinca/vim-quickrun'

